USE stayfor;

DROP TABLE IF EXISTS TERMS;
DROP TABLE IF EXISTS NOTICE;
DROP TABLE IF EXISTS FAQ;
DROP TABLE IF EXISTS QNA;
DROP TABLE IF EXISTS WISHLIST;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS BLOCKEDGUEST;
DROP TABLE IF EXISTS ATTRACTION;
DROP TABLE IF EXISTS ACCOMM_REVIEWS;
DROP TABLE IF EXISTS REVIEWS_TAGS;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS ACCOMM_FORSALE_EXCEPT;
DROP TABLE IF EXISTS ACCOMM_FACILITY;
DROP TABLE IF EXISTS ACCOMM_FORSALE;
DROP TABLE IF EXISTS ACCOMM_PHOTO;
DROP TABLE IF EXISTS ACCOMM_INFO;
DROP TABLE IF EXISTS FACILITY;
DROP TABLE IF EXISTS CHATLIST;
DROP TABLE IF EXISTS HOSTLIST;
DROP TABLE IF EXISTS NOTIFICATION;
DROP TABLE IF EXISTS MEMBERS;

CREATE TABLE MEMBERS( 
USER_ID VARCHAR(50) PRIMARY KEY,
PASSWD VARCHAR(60) NOT NULL,
PASSWD_DATE DATE NOT NULL,
SIGNUP_DATE DATE NOT NULL,
TERMS VARCHAR(6) NOT NULL,
TELEPHONE VARCHAR(11) UNIQUE,
INTRODUCE VARCHAR(200),
ADDRESS VARCHAR(100),
PHOTO VARCHAR(200),
ROLES VARCHAR(10) DEFAULT "ROLE_USER"
);

CREATE TABLE NOTIFICATION (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
USER_ID VARCHAR(50),
MESSAGE TEXT,
LINK_URL VARCHAR(255),
IS_READ BOOLEAN DEFAULT false,
CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,

CONSTRAINT NOTIFICATION_USER_FK FOREIGN KEY (USER_ID) REFERENCES MEMBERS(USER_ID)
);

CREATE TABLE FACILITY( 
FAC_ID VARCHAR(20) PRIMARY KEY,
FACNAME VARCHAR(100) NOT NULL,
FACLOGO VARCHAR(200)
);

CREATE TABLE ACCOMM_INFO( 
ACCOMM_ID VARCHAR(20) PRIMARY KEY,
ACCOMM_NAME VARCHAR(100) NOT NULL,
HOST_ID VARCHAR(50),
ADD1 VARCHAR(20),
ADD2 VARCHAR(20),
ADD3 VARCHAR(20),
ADD4 VARCHAR(30),
ADD5 VARCHAR(30),
POSITIONX DOUBLE NOT NULL,
POSITIONY DOUBLE NOT NULL,
PARKINGX DOUBLE,
PARKINGY DOUBLE,
PEOPLE TINYINT NOT NULL,
BATH TINYINT NOT NULL,
ROOM TINYINT NOT NULL,
BED TINYINT NOT NULL,
COMMENTS VARCHAR(300),
CHECKIN_TIME VARCHAR(5) NOT NULL,
CHECKOUT_TIME VARCHAR(5) NOT NULL,
REGIST_DATE DATE NOT NULL,
TOTAL TINYINT NOT NULL DEFAULT 0,

CONSTRAINT ACCOMM_INFO_HOSTID_FK FOREIGN KEY (HOST_ID) REFERENCES MEMBERS(USER_ID)
);

CREATE TABLE ACCOMM_FACILITY( 
ACCOMM_ID VARCHAR(20),
FAC_ID VARCHAR(20),

CONSTRAINT ACCOMM_FACILITY_PK PRIMARY KEY(ACCOMM_ID, FAC_ID),

CONSTRAINT ACCOMM_FACILITY_ACCOMMID_FK FOREIGN KEY (ACCOMM_ID) REFERENCES ACCOMM_INFO(ACCOMM_ID),
CONSTRAINT ACCOMM_FACILITY_FK FOREIGN KEY (FAC_ID) REFERENCES FACILITY(FAC_ID)
);
CREATE TABLE ACCOMM_PHOTO( 
ACCOMM_ID VARCHAR(20),
SEQ TINYINT,
LINK VARCHAR(200) NOT NULL,

CONSTRAINT ACCOMM_PHOTO_PK PRIMARY KEY(ACCOMM_ID, SEQ),

CONSTRAINT ACCOMM_ID_FK FOREIGN KEY (ACCOMM_ID) REFERENCES ACCOMM_INFO(ACCOMM_ID)
);

CREATE TABLE ACCOMM_FORSALE(
ACCOMM_ID VARCHAR(20),
PRICE BIGINT NOT NULL,
DISCOUNT TINYINT,
SALE_DATE DATE NOT NULL,
RNUM TINYINT,

CONSTRAINT ACCOMM_FORSALE_PK PRIMARY KEY(ACCOMM_ID, SALE_DATE, RNUM),

CONSTRAINT ACCOMM_ID_FORSALE_FK FOREIGN KEY (ACCOMM_ID) REFERENCES ACCOMM_INFO(ACCOMM_ID)
);

CREATE TABLE RESERVATION( 
RESERVE_ID VARCHAR(20) PRIMARY KEY,
USER_ID VARCHAR(50),
ACCOMM_ID VARCHAR(20),
CHECKIN_DATE DATE NOT NULL,
CHECKOUT_DATE DATE NOT NULL,
CHECKIN_TIME VARCHAR(5) NOT NULL,
PEOPLE TINYINT NOT NULL,
MEMO VARCHAR(200),
RESERVE_DATE DATE NOT NULL,
STAT CHAR NOT NULL,

CONSTRAINT RESERVATION_USERID_FK FOREIGN KEY (USER_ID) REFERENCES MEMBERS(USER_ID),
CONSTRAINT RESERVATION_ACCOMMID_FK FOREIGN KEY (ACCOMM_ID) REFERENCES ACCOMM_INFO(ACCOMM_ID)
);

CREATE TABLE PAYMENT( 
USER_ID VARCHAR(50),
PAYMENT_TID VARCHAR(20),
RESERVE_ID VARCHAR(20),
PRICE BIGINT NOT NULL,
PAYMENT_DATE DATE NOT NULL,
STAT CHAR NOT NULL,

CONSTRAINT PAYMENT_PK PRIMARY KEY(USER_ID, PAYMENT_TID),

CONSTRAINT PAYMENT_USERID_FK FOREIGN KEY (USER_ID) REFERENCES MEMBERS(USER_ID),
CONSTRAINT PAYMENT_RESERVEID_FK FOREIGN KEY (RESERVE_ID) REFERENCES RESERVATION(RESERVE_ID)
);

CREATE TABLE REVIEWS_TAGS(
TAG_ID VARCHAR(20) PRIMARY KEY,
TAGNAME VARCHAR(100) NOT NULL
);

CREATE TABLE ACCOMM_REVIEWS( 
USER_ID VARCHAR(50),
RESERVE_ID VARCHAR(20) PRIMARY KEY,
ACCOMM_ID VARCHAR(20),
PHOTO VARCHAR(200),
PHOTO2 VARCHAR(200),
PHOTO3 VARCHAR(200),
CONTENT VARCHAR(500) NOT NULL,
REGIST_DATE DATE NOT NULL,
TAG VARCHAR(20),
TAG2 VARCHAR(20),
TAG3 VARCHAR(20),

CONSTRAINT ACCOMMREVIEWS_USERID_FK FOREIGN KEY (USER_ID) REFERENCES MEMBERS(USER_ID),
CONSTRAINT ACCOMMREVIEWS_RESERVEID_FK FOREIGN KEY (RESERVE_ID) REFERENCES RESERVATION(RESERVE_ID),
CONSTRAINT ACCOMMREVIEWS_ACCOMID_FK FOREIGN KEY (ACCOMM_ID) REFERENCES ACCOMM_INFO(ACCOMM_ID),
CONSTRAINT ACCOMMREVIEWS_TAG_FK FOREIGN KEY (TAG) REFERENCES REVIEWS_TAGS(TAG_ID),
CONSTRAINT ACCOMMREVIEWS_TAG2_FK FOREIGN KEY (TAG2) REFERENCES REVIEWS_TAGS(TAG_ID),
CONSTRAINT ACCOMMREVIEWS_TAG3_FK FOREIGN KEY (TAG3) REFERENCES REVIEWS_TAGS(TAG_ID)

);

CREATE TABLE ATTRACTION( 
ATTR_ID VARCHAR(20) PRIMARY KEY,
LINK VARCHAR(200),
ATTR_NAME VARCHAR(50),
ADD1 VARCHAR(20),
ADD2 VARCHAR(20),
ADD3 VARCHAR(20),
ADD4 VARCHAR(30),
ADD5 VARCHAR(30),
PHOTO VARCHAR(200)
);

CREATE TABLE BLOCKEDGUEST( 
HOST_ID VARCHAR(50),
BLOCKED_ID VARCHAR(50),
BLOCKED_DATE DATE NOT NULL,

CONSTRAINT BLOCKEDGUEST_PK PRIMARY KEY(HOST_ID, BLOCKED_ID),

CONSTRAINT BLOCKEDGUEST_HOSTID_FK FOREIGN KEY (HOST_ID) REFERENCES MEMBERS(USER_ID),
CONSTRAINT BLOCKEDGUEST_BLOCKEDID_FK FOREIGN KEY (BLOCKED_ID) REFERENCES MEMBERS(USER_ID)

);

CREATE TABLE HOSTLIST(
HOST_ID VARCHAR(50),
CEO VARCHAR(100),
BIZNAME VARCHAR(100),
BIZNUM VARCHAR(30),

CONSTRAINT HOSTLIST_PK PRIMARY KEY(HOST_ID, BIZNUM),

CONSTRAINT HOSTLIST_HOSTID_FK FOREIGN KEY (HOST_ID) REFERENCES MEMBERS(USER_ID)
);

CREATE TABLE CHATLIST( 
CHAT_ID VARCHAR(20) UNIQUE,
GUEST_ID VARCHAR(50) NOT NULL,
HOST_ID VARCHAR(50) NOT NULL,

CONSTRAINT CHATLIST_PK PRIMARY KEY(GUEST_ID, HOST_ID),

CONSTRAINT CHATLIST_GUEST_ID FOREIGN KEY (GUEST_ID) REFERENCES MEMBERS(USER_ID),
CONSTRAINT CHATLIST_HOST_ID FOREIGN KEY (HOST_ID) REFERENCES HOSTLIST(HOST_ID)
);
select * from CHATLIST;

CREATE TABLE MESSAGE(
SENDER VARCHAR(50) NOT NULL,
RECEIVER VARCHAR(50) NOT NULL,
CONTENT VARCHAR(300) NOT NULL,
SEND_DATE DATETIME NOT NULL,

CONSTRAINT MESSAGE_SENDER_FK FOREIGN KEY (SENDER) REFERENCES MEMBERS(USER_ID),
CONSTRAINT MESSAGE_RECEIVER_FK FOREIGN KEY (RECEIVER) REFERENCES MEMBERS(USER_ID)
);

CREATE TABLE WISHLIST( 
USER_ID VARCHAR(50),
ACCOMM_ID VARCHAR(20),

CONSTRAINT WISHLIST_PK PRIMARY KEY(USER_ID, ACCOMM_ID),

CONSTRAINT WISHLIST_USERID_FK FOREIGN KEY (USER_ID) REFERENCES MEMBERS(USER_ID),
CONSTRAINT WISHLISTE_ACCOMMID_FK FOREIGN KEY (ACCOMM_ID) REFERENCES ACCOMM_INFO(ACCOMM_ID)
);

CREATE TABLE QNA(
QNA_ID VARCHAR(8) PRIMARY KEY,
TITLE VARCHAR(300) NOT NULL,
CONTENT VARCHAR(500) NOT NULL,
USER_ID VARCHAR(50),
WRITE_DATE DATETIME NOT NULL,
REPLY VARCHAR(500),

CONSTRAINT QNA_USERID_FK FOREIGN KEY (USER_ID) REFERENCES MEMBERS(USER_ID)
);

CREATE TABLE FAQ(
FAQ_ID VARCHAR(8) PRIMARY KEY,
QUESTION VARCHAR(300) NOT NULL,
ANSWER VARCHAR(500) NOT NULL
);

CREATE TABLE NOTICE(
NOTICE_ID VARCHAR(8) PRIMARY KEY,
WRITE_DATE DATE NOT NULL,
TITLE VARCHAR(100) NOT NULL,
CONTENT VARCHAR(500) NOT NULL
);

CREATE TABLE TERMS(
TERMS_ID VARCHAR(8) PRIMARY KEY,
TERMS_TITLE VARCHAR(300) NOT NULL,
TERMS_CONTENT VARCHAR(2000) NOT NULL,
TERMS_REQUIRED VARCHAR(1) NOT NULL,
CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ACCOMM_FORSALE_EXCEPT (
  ACCOMM_ID VARCHAR(20),
  EXCEPT_DATE DATE NOT NULL,

  CONSTRAINT ACCOMM_EXCEPT_PK PRIMARY KEY (ACCOMM_ID, EXCEPT_DATE),
  CONSTRAINT ACCOMM_ID_EXCEPT_FK FOREIGN KEY (ACCOMM_ID)
    REFERENCES ACCOMM_FORSALE(ACCOMM_ID)
    ON DELETE CASCADE
);
